server:
  port: 9090
spring:
  profiles:
    include: oauth
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/health_partner?serverTimezone=Asia/Seoul
      username: root
      password: ms1024!33
  data:
    redis:
      host: redis-17942.c325.us-east-1-4.ec2.redns.redis-cloud.com
      port: 17942
      password: yz7a34MkKxG2l9IhAp1TwhAl4ERcDza2
    mongodb:
      uri: mongodb+srv://jagalji33:xUWcAX8djGrNKxyc@cluster0.miahl92.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: HealthPartnerDB
  mail:
    host: smtp.gmail.com
    port: 587
    username: jagalji33@gmail.com
    password: enhybzulsmpyvuvc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    s3:
      bucket: studentmsawsbucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAW3MD73HLQ4NFZ65M
      secretKey: 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

mzen:
  secretKey: 8ZcskwShapZjaTsOEAyi%2FH6j66Q98M0c2q%2BJ6DHxWAqNqLw5KPO1dYEp8XVIYJ8YHXaRq4VDMjcCWK6N0Qn8lw%3D%3D

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33

logging:
  level:
    org:
      springframework:
        security: DEBUG